<?php
/*-----------------------------------------------------------------------*
   Copyright (c) 2007 by Dominique Laporte(C-E-D@wanadoo.fr)

   This file is part of Prométhée.

   Prométhée is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   Prométhée is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with Prométhée.  If not, see <http://www.gnu.org/licenses/>.
*-----------------------------------------------------------------------*/
?>

<?php
/*
 *		module   : config.php
 *		projet   : définition des messages
 *
 *		version  : 1.0
 *		auteur   : laporte
 *		creation : 05/04/2007
 *		modif    : 
 *
 */

//---------------------------------------------------------------------------
static	$message = Array(

"<strong>Configuration de l'intranet</strong>",
"personnalisation",
"base de données",
"menus",
"<strong>. Sécurité</strong>",
"Connexion persistante :",
"Création de compte :",
"par les utilisateurs",
"Durée de validité :",
"des comptes (aaaa-mm-jj)",
"Filtrage IP :",
"Mode DEBUG :",
"Mode DEMO :",
"(connexions multiples sous le même ID)",
"Mot de passe :",
"caractére(s)",
"Délai des pages :",
"minutes",
"Délai des liens :",
"jours",
"<strong>. Données</strong>",
"Taille des fichiers :",
"Quotas disque :",
"Durée des logs :",
"Durée des stats :",
"Durée des post-it :",
"semaines",
"<strong>. Affichage</strong>",
"Menus :",
"2 colonnes,gauche,droite",
"Espacement :",
"pixel(s)",
"Page d'accueil :",
"flash info par défaut",
"Données par page :",
"Nombre de pages :",
"Derniers messages :",
"forum style egroup",
"<strong>. Documents autorisés</strong>",
"Modifier",
"Créer",
"- extension :",
"ajouter un document",
"pour valider la configuration.",
"pour revenir à l'accueil.",
"<strong>Configuration de la base de données</strong>",
"<strong>. Centres constitutifs</strong>",
"visible",
"invisible",
"supprimer",
"ajouter un enregistrement",
"<strong>. Groupes utilisateurs</strong>",
"droits étendus",
"droits limités",
"<strong>. Classes/Filières/Formations</strong>",
"<strong>. Matières/UV/Modules</strong>",
"<em>afin de personnaliser votre intranet, veuillez compléter le formulaire suivant</em>",
"Prométhée, l'ENT « clef en main » Libre et gratuit",
"Bienvenue sur votre intranet",
"Veuillez taper votre ID utilisateur et votre mot de passe pour vous connecter.",
"Erreur à la création de \"%1\" : vérifiez que vous possédez les droits d'écriture.",
"Erreur à la création de %1 : vérifiez que vous possédez les droits d'écriture.",
"Bravo, vous avez réussi à paramétrer votre intranet !<br/><br/>
Il vous reste à créer les comptes :<br/>
%1 des utilisateurs avec phpMyAdmin (base %2, table user_id).<br/>
%3 des %4 avec phpMyAdmin (base %5, table user_student).<br/><br/>
Pour tester l'intranet, utilisez le compte administrateur \"<strong>%6</strong>\" (pas de mot de passe).<br/>
Pour vous connecter maintenant cliquez <a href=\"%7\">ici</a>.",
"options",
"choisissez un menu :",
"nouvel intitulé :",
"<strong>sous menu</strong>",
"ne pas afficher le lien",
"afficher le lien",
"Personnalisation de l'intranet : %1/2",
"<strong>Attention :</strong> veuillez indiquer le nom de votre établissement.",
"Le \"nom\" de votre établissement est utilisé pour créer un répertoire images/logos/\"nom\" où seront copiés le logo de votre établissement (logo01.jpg) ainsi que celui de votre région (logo02.jpg).",
"<strong>Nom établissement :</strong>",
"obligatoire",
"Taille maximale conseillée du logo établissement : 700 x 110.",
"<strong>Logo établissement :</strong>",
"Taille maximale conseillée du logo région : 100 x 50.",
"<strong>Logo région :</strong>",
"La couleur du thème est celle utilisée pour l'intranet. Elle doit correspondre à votre charte graphique.",
"<strong>Attention:</strong> veuillez indiquer l'adresse de votre établissement.",
"<strong>Adresse :</strong>",
"<strong>Attention:</strong> veuillez indiquer le téléphone de votre établissement.",
"<strong>Tél :</strong>",
"<strong>Fax :</strong>",
"<strong>Site web :</strong>",
"<strong>Email :</strong>",
"Indiquez ici le type de votre établissement",
"Suivant >>",
"La base de données va être paramétrée en fonction du type de votre établissement.<br/>Veuillez indiquer les centres constitutifs (ie : collège et lycée) qui composent votre établissement.",
"<strong>Type établissement :</strong>",
"Pour terminer l'installation cliquez ici",
"Envoyer",
"Erreur création %1 (%2)",
"<strong>Personnalisation de l'intranet</strong>",
"choisissez une configuration :",
"<strong>Thème :</strong>",
"appliquer aux menus",
"<strong>Puces graphiques :</strong>",
"<strong>Fond graphique :</strong>",
"appliquer à la page",
"<strong>Barre des Titres :</strong>",
"<strong>Couleur du bandeau :</strong>",
"<strong>Adresse :</strong>",
"<strong>Logos :</strong>",
"<a href=\"%1\">logo principal</a>",
"Gauche",
"Centré",
"Droite",
"<strong>Titre de fenêtre :</strong>",
"<strong>Message d'accueil :</strong>",
"Connexion :",
"aide",
"modification du lien",
"nouveau lien",
"insertion",
"modification",
"<strong>Gestionnaire de menus</strong><br/><em>Veuillez compléter le formulaire suivant pour paramétrer le lien</em>",
"<strong>Statut :</strong>",
"<strong>Auteur :</strong>",
"<strong>Liste :</strong>",
"<strong>Attention :</strong> l'intitulé doit être renseigné.",
"<strong>Intitulé</strong>",
"<strong>Attention :</strong> l'url doit être renseignée.",
"<strong>URL</strong> (une adresse internet doit débuter par http://)",
"<strong>Accès visible</strong>",
"<strong>Autorisations</strong>",
"Fermer le lien",
"Accès anonyme",
"ajouter un lien",
"pour revenir sur la page précédente.",
"- public :",
"- validité :",
"<a href=\"%1\" onclick=\"window.open(this.href, '_blank'); return false;\">logo région</a>",
"Langues autorisées :",
"<strong>Image</strong>",
"ajouter un menu",
"modifier un menu",
"nouveau menu",
"<strong>Texte</strong>",
"<strong>Alignement</strong>",
"<strong>Affichage</strong>",
"fermer le menu",
"défilement",
"Bienvenue sur la page %1.",
"<strong>Pictogramme</strong>",
"<strong>Contenu</strong>",
"<strong>. SMS</strong>",
"Service SMS :",
"<strong>Webmestre :</strong>",
"Installer",
"Désinstaller",
"P2P",
"<strong>Clef :</strong>",
"Connexion",
"Obtenir une clef",
"<strong>Partage :</strong>",
"<strong>Maintenance :</strong>",
"Choisissez un centre :",
"<strong>Filtrage :</strong>",
"<strong>Filtrage des accès</strong>",
"du",
"au",
"aaaa-mm-jj",
"Encodage :",
"== personnalisé ==",
"Backoffice",
"trier les items",
"Activé",
"Désactivé",
"<strong>Taille</strong>",
"Ko",
"<strong>Serveur :</strong>",
"<strong>Configuration du P2P</strong>",
"<strong>Configuration des menus</strong>",
"<strong>Configuration des mot-clefs</strong>",
"Mot-clefs",
"<strong>Synchronisation :</strong>",
"lancer la synchronisation",
"Documents",
"Annuaire",
"<strong>Robot d'indexation :</strong>",
"<strong>Code postal + ville :</strong>",
"Fuseau horaire",
"Architecture",
"bits",
"[nouveau]",
"[répondre]",
"[valider]",
"[annuler]",
"<strong>Couleur bandeau menu haut :</strong>",
"Emploi du temps",
"Vacances",
"Configuration semaine paire/impaire",
"Configuration des vacances",
"Couleur",
"Semaine",
"au"
);
//---------------------------------------------------------------------------
?>